### ISSUE TITLE
itbz/fpdf 

### ISSUE THREAD

**Issue by Gladhon** [ravage84/SwissPaymentSlipFpdf#17]
itbz/fpdf  is abandoned, you should change to setasign/fpdf 
maybe, than the package will support php8 ?

**Comment by rebruCH** [comment]
@Gladhon 
You have to load the setasign/fpdf in your composer.json, then you can use the setasign/fpdi. You have to change your code slightly, because the calls are different.

But the SwissPaymentSlipFpdf supports already the setasign.

**Comment by Gladhon** [comment]
@rebruCH cool, but as you require itbz/fpdf in the project composer.json, it will be always installed - and i get a notification, that i'm using abandoned libs.

**Comment by rebruCH** [comment]
@Gladhon Thats true, but you can ignore that. Dont know if they ever will remove the abandoned library.

**Comment by ravage84** [comment]
I'm not going to implement or action this, anymore, as this package has become obsolete due to the introduction of the [Swiss QR code payment slip](https://de.wikipedia.org/wiki/QR-Rechnung) and the discontinuation of the old ESR.

One can use https://github.com/sprain/php-swiss-qr-bill for the new Swiss QR  bill.
